[#126]  신청서(proposal) 작성 API 생성
prgrms-web-devcourse/Team-Kkini-Mukvengers-BE pull request #128
Opened 2023-03-08 09:02 UTC by hikarigin99

### 🌱 작업 사항 
- 신청서를 작성하는 API를 생성하였습니다.
- 신청서를 생성하기 전 `여러 검증`이 필요합니다.
  - 사용자가 존재하는 사용자인지 & 밥모임이 존재하는 밥모임인지
  - 해당 밥모임의 모집 인원이 다 차서 신청할 수 없는 경우
  - 이미 신청한 밥모임에 다시 신청서를 작성하는 경우 (중복 신청 방지)
  - 강퇴된 사용자가 해당 밥모임에 다시 신청하는 경우 (강퇴 유저)
  - 해당 밥모임의 방장이 신청서를 작성하는 경우

- 각 검증에 대한 실패 테스트를 작성하였습니다.
 
### ❓ 리뷰 포인트
- CrewMemberRole에 따른 검증은 `메시지만 다르지 똑같은 예외`가 터지는 것이라 생각해 `IllegalStateException` 처리한 상태입니다. 
따로 Custom Exception으로 처리하는 것이 좋을까요? 그렇다면 총 Exception 클래스는 4개가 나올 것으로 예상되며
 [feat: Custom Exception 으로 변경시 사용될 ErrorCode](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/228e75cd3b6392245b7b02f83837ad1b132b20ba) 처럼 `HttpStatus.FORBIDDEN` 상태 코드를 두려고 하는데 어떻게 생각하시나요?
- 혹시 제가 빠트린 다른 검증 로직이 있을까요?

### 🦄 관련 이슈
resolves #126

2023-03-08 09:46 UTC, rlarltj approved these changes
신청서 작업하시느라 고생 많으셨습니다!

1. `CrewMemberRole` 관련 검증에서 메시지만 다른 똑같은 예외가 발생한다고 하셨어요.  
-> Custom Exception 클래스가 한개면 충분할 것 같습니다!! 

2. 상태코드로 관리하는 것은 좋은 생각인 것 같습니다.
 
3. 검증도 충분한 것 같습니다.

2023-03-08 09:46 UTC, rlarltj commented on src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
> +	public IdResponse create(CreateProposalRequest proposalRequest, Long userId, Long crewId) {
Transactional 누락된 것 같습니다!

2023-03-08 09:53 UTC, hikarigin99 commented on src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
> +	public IdResponse create(CreateProposalRequest proposalRequest, Long userId, Long crewId) {
헉 이런 실수를.. 감사합니다🥹

2023-03-08 14:41 UTC, geonwoo0215 requested changes
이슈 번호와 브랜치 번호가 다릅니다. 
아마 실수라 생각합니다. 
별 문제 없다면 현 브렌치에서 진행해주세요
신청서 생성 로직에서 고려해야 될 부분이 많아 보입니다.
코드를 짜시면서 많은 검증에 대해 고려하신 게 보입니다.👍
신청서 생성에 누락된 검증(중복 신청)을 추가해 주세요.

CrewMemberRole 따른 거라면 정원초과는 다른경우이기 때문에 3가지가 같은 경우 아닌가요?
정원 초과는 Role 과는 다르기 때문에 Role에서 생기는 에러와는 다르게 구분되어야 한다고 생각합니다.
HttpStatus.FORBIDDEN -> 호출하는 api 에대한 권한이 없어 403을 사용해도 괜찮다고 생각합니다.

2023-03-08 14:41 UTC, geonwoo0215 commented on src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
> +
검증이 누락되었습니다.
모임의 신청서를 작성하였고 그 신청서가 대기중이라면 중복신청을 막아야합니다.
신청서 테이블을 한번 조회하고 조회된 신청서의 상태가 대기중인것이 있는지 알아야 합니다.
조회는 다건조회일것으로 예상됩니다.
신청서가 단순히 거절된다면 다시 신청서를 작성할 수 있기 때문에 같은 사용자의 같은 모임에 대한 신청서가 여래개 저장될 수 있을겁니다.

2023-03-08 14:41 UTC, geonwoo0215 commented on src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
> +				case MEMBER -> throw new IllegalStateException(DUPLICATE_USER_EXCEPTION_MESSAGE);
에러메시지를 enum 클래스로 관리하고 필드로 CrewMemberRole과 Message를 가져서 Role에 대응하는 Message를 준다면 switch case문은 없앨 수 있다고 생각합니다.
ex) throw new IllegalStateException(Error.getMessage(crewMember.get().getCrewMemberRole()));
하지만 switch case 문이 나빠보이진 않습니다.
CrewMemberRole이 더 확장될 가능성이 없다고 판단되고, 역할에 대한 에러가 3개라면 enum 클래스로 만들어서 따로 관리할 필요성은 없다고 생각합니다.
은비님이 판단하에 에러메시지를 따로 service가 아닌 enum클래스에서 관리하고, 확장을 고려하여 switch case보다 주입하는 Role에따라 메시지를 처리하고 싶다면 enum을 사용하시고 아니면 이렇게 하셔도 괜찮다고 생각합니다.

2023-03-08 18:41 UTC, JoosungKwon approved these changes
일단 은비님 신청서 작성에 대한 API를 만드시느라 고생하셨습니다! 여러 상황에 대한 검증과 그에 따른 테스트 까지.. 많이 노력하신게 보입니다 👍
예외에 대한 저의 생각은 저 였다면 4가지 경우에 대해 모든 예외를 만들지 않았을까 생각합니다! 근데 예외 코드가 저희만 사용하기 보다 프론트에서도 코드에 대한 핸들링이 필요하기 때문에 프론트와도 일정 부분 협의가 필요할 것 같습니다! 메시지와 에러 코드를 어떻게 관리할 것인가에 대해 저 또한 아직 정답을 모르겠습니다. 시간이 된다면 프로젝트 전에, 아니면 후에 리팩토링 할 때 라도 다시 한번 정해보는 시간이 있어야 할 것 같습니다! 좀 더 세세한 리뷰는 댓글로 남겨놓았습니다~!

2023-03-08 18:41 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
> +	 * @return status : 201, body : 생성된 신청서 조회 redirectUrl
정확하게 말하자면 body가 아닌 헤더에 Location 필드에 redirectUrl 주소가 들어갑니다~

2023-03-08 18:41 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
> +	public ResponseEntity<IdResponse> create
/proposals/{crewId} 는 별로인가요..?

2023-03-08 18:41 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
> +		URI location = UriComponentsBuilder.fromUriString("/api/v1/proposals/" + proposal.id()).build().toUri();
"/api/v1/proposals/" + proposal.id() 아직 조회 API는 없는것이죠..?

2023-03-08 18:41 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
> +				case LEADER -> throw new IllegalStateException(LEADER_USER_EXCEPTION_MESSAGE);
ProposalException을 만들고 내부적으로 static 메서드를 제공하는 방식으로 해도 좋을 것 같다고 생각이 드네요! 메세지 또한 예외 객체에서 관리할 수 있게 될 것 같습니다! 아니면 건우님이 이야기하신 Enum도 나쁘지 않을 것 같습니다!

2023-03-08 18:41 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
> +	PROPOSAL_BLOCKED_USER(HttpStatus.FORBIDDEN, "P001", "강퇴된 밥모임에는 신청서를 작성할 수 없습니다."),
저는 다양한 상황에 대해 여러 예외 코드를 만드는 방식을 좋아하긴 합니다만, 이부분은 프론트와도 협의가 필요할 것입니다. 그리고 403에러는 보통 권한 없음 에러여서 시큐리티에서 처리하는 에러임을 뜻하기는 합니다. 하지만, 의미 자체에는 문제가 없으니 사용하는 것이 좋은 것 같습니다!

2023-03-09 09:33 UTC, geonwoo0215 approved these changes

2023-03-09 09:34 UTC, merged