[#5] ERD를 바탕으로 도메인 엔티티 구현
prgrms-web-devcourse/Team-Kkini-Mukvengers-BE pull request #9
Opened 2023-02-20 16:29 UTC by JoosungKwon

### 🌱 작업 사항 
- 기본 필드 설정
- 연관 관계 설정
### ❓ 리뷰 포인트
- 혹시 놓친건 없는지 한번 더 확인 부탁드립니다~!
### 🦄 관련 이슈
#5

2023-02-20 16:50 UTC, geonwoo0215 requested changes

2023-02-20 16:50 UTC, geonwoo0215 commented on src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
> +	@GeneratedValue(strategy = AUTO)
제가 실수로 auto로 해버렸네요... 이부분과 store가 identity로 수정되어야 합니다.

2023-02-21 05:02 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
> +	@GeneratedValue(strategy = AUTO)
아 이거 확인 못했네요!! 바로 정정할게요

2023-02-21 05:14 UTC, geonwoo0215 approved these changes

2023-02-21 05:18 UTC, rlarltj approved these changes
도메인 엔티티 만드시느라 고생하셨습니다~

2023-02-21 05:18 UTC, rlarltj commented on src/main/java/com/prgrms/mukvengers/domain/proposal/model/Proposal.java
> +	}
메소드 명 validateContent는 어떠신가요?!

2023-02-21 05:18 UTC, rlarltj commented on src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
> +	@GeneratedValue(strategy = AUTO)
이부분도 IDENTITY로 변경해야 할 것 같아요!

2023-02-21 05:18 UTC, rlarltj commented on src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
> +	private Category category;
`length = 255`는  생략해도 괜찮지 않을까?요?!

2023-02-21 05:22 UTC, hikarigin99 approved these changes
확인했습니다 고생하셨어요👍

2023-02-21 05:22 UTC, hikarigin99 commented on src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
> +public class User extends BaseEntity {
@Table(name = "users") 안써도 되나요👀

2023-02-21 05:24 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/proposal/model/Proposal.java
> +	}
아 동사로 하는게 좋은 거 같아요!! 수정하겠습니다 👍

2023-02-21 05:25 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
> +	@GeneratedValue(strategy = AUTO)
수정했습니다~!

2023-02-21 05:25 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
> +	private Category category;
아 디폴트 값이 군요 생략할게요~!!

2023-02-21 05:26 UTC, JoosungKwon commented on src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
> +public class User extends BaseEntity {
아.. 써야합니다! 추가할게요~!!

2023-02-21 05:44 UTC, merged